apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-backend
    namespace: default
    labels:
        app: auth-server
spec:
    replicas: 2
    selector:
        matchLabels:
            app: auth-server
    template:
        metadata:
            labels:
                app: auth-server
        spec:
            containers:
                - name: web
                  image: nginx:alpine
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: auth-backend-svc
    namespace: default
    annotations:
        kuberun.com/run: "true"
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: 8080
    selector:
        app: auth-server
