apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
  namespace: default
  labels:
    app: auth-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend-svc
  namespace: default
  annotations:
    kuberun.com/run: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 8080
      targetPort: 80
      name: doublehttp
    - port: 9090
      targetPort: 80
      name: wierdhttp
  selector:
    app: auth-server
