apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: fluentbit-indexer
    namespace: default
    labels:
        app: log-collector
spec:
    selector:
        matchLabels:
            app: log-collector
    template:
        metadata:
            labels:
                app: log-collector
        spec:
            containers:
                - name: fluentbit
                  image: fluent/fluent-bit:latest
                  ports:
                      - containerPort: 5140
---
apiVersion: v1
kind: Service
metadata:
    name: log-router-svc
    namespace: default
    annotations:
        kuberun.com/run: "true"
spec:
    type: ClusterIP
    ports:
        - port: 514
          targetPort: 5140
    selector:
        app: log-collector
