apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kuberun-agent
  namespace: default
  labels:
    app: kuberun-agent
spec:
  selector:
    matchLabels:
      name: kuberun-agent
  template:
    metadata:
      labels:
        name: kuberun-agent
    spec:
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: agent
          image: youssefkali/kuberun-agent:v0.2.0
          imagePullPolicy: Always
          ports:
            - name: updates
              containerPort: 4443
              hostPort: 4443
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          volumeMounts:
            - name: config-volume
              mountPath: /etc/agent-config
              readOnly: true
            - name: host-netns
              mountPath: /var/run/netns
              readOnly: true
            - name: hostproc
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: kuberun-agent-config
        - name: host-netns
          hostPath:
            path: /var/run/netns
        - name: hostproc
          hostPath:
            path: /proc
---
apiVersion: v1
kind: Service
metadata:
  name: kuberun-agent
  namespace: default
  labels:
    app: kuberun-agent
spec:
  clusterIP: None
  selector:
    name: kuberun-agent
  ports:
    - name: http-api
      port: 4443
      targetPort: 4443
