apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberun-agent-config
  namespace: default
data:
  config.yml: |
    kube_run_controller: "kuberun-controller.default.svc.cluster.local:4444"
    update: false
    ips:
    headless_map:
