{{- include "kuberun.validateNamespace" . -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberun-controller-role
rules:
  # 1. Watch, list, create, and EDIT services across ALL namespaces
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # 2. Get/List/Watch information on Pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  # This grants get/list/watch, plus update/patch and scale subresource rights
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "deployments/scale"
      - "replicasets"
      - "statefulsets"
      - "statefulsets/scale"
      - "daemonsets"
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

  # 4. Edit a SPECIFIC configmap only
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [ "{{ .Values.agent.configMapName }}" ]
    verbs: ["get", "update", "patch"]
{{- end -}}
