{{- include "kuberun.validateNamespace" . -}}
{{- if .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuberun.controllerServiceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end -}}
