apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  labels:
    app: datastore
spec:
  serviceName: "database-svc"
  replicas: 4
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "mysecurepassword"
---
apiVersion: v1
kind: Service
metadata:
  name: database-svc
  labels:
    kuberun/run: "true"
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: datastore
